### PR TITLE
remove hardcoded push destination in import_contrail_container.sh

### PR DESCRIPTION
**Pull request by Lnic**
Push destination is currently hardcoded in  "_import_contrail_container.sh_" , I add option "_-d destination_" to allow the push on custom destination.

### CODE REVIEW

**Comment by alexey-mr** [comment]
This repository was moved under review system.
So PR now is not possible to merge.
Could you create review with your change.

**Comment by Lnic** [comment]
Hello, 
I'm not very familiar with this system, is it the same as Openstack ? git-review witht gerrit ?

**Comment by Andrey-mp** [comment]
Yes, it's the same.
https://review.opencontrail.org/#/q/project:Juniper/contrail-tripleo-heat-templates

**Comment by Lnic** [comment]
Ok thanks, I registered myself and waiting for my contributor agreement to be accepted. (this mail address seem to be not functional at the moment ci-admin@opencontrail.org)

**Pull request closed without merging**
